In [1]:
from RMDL import RMDL_Text as RMDL
import pandas as pd
import numpy as np
import nltk

from nltk.corpus import reuters
from sklearn.preprocessing import MultiLabelBinarizer

sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/zer0deck/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [2]:
from sklearn.model_selection import train_test_split
df = pd.read_csv('../Data/FilteredData.csv', sep= ';', index_col=False)
training_data, testing_data = train_test_split(df,random_state = 2000)
Y_train=np.array(training_data['Class'].values)
Y_test=testing_data['True class'].values
X_train = training_data['CleanedText'].values
X_test = testing_data['CleanedText'].values
Y_train = np.argmax(Y_train, axis=0)
print (Y_train)
df.head(7)

3


CleanedText  \
0  runner around world post photo wearing space r...   
1  wfh time pfh read prachar politics home politi...   
2  bts system last collection accessory product t...   
3  manohar parrikar always idol resigning party t...   
4  day 1394 running min 10 km day total 16448 km ...   
5           win italy 1 66 switzerland 6 0 draw 3 85   
6  cannot reproduced easily economically able bri...   

                                       TokenizedText  \
0  ['runner', 'runner', 'explorer', 'runner', 'se...   
1  ['time', 'high', 'time', 'contestant', 'creati...   
2            ['product', 'two', 'hat', 'two', 'hat']   
3  ['parrikar', 'party', 'party', 'parrikar', 'ra...   
4                 ['km', 'day', '16448', 'km', '03']   
5       ['italy', '66', 'switzerland', 'draw', '85']   
6  ['easily', 'bring', 'highest', 'shortest', 'po...   

                                              TF-IDF  TF-IDF sum  \
0  [1.43509015 3.43247292 0.53856938 8.20984681 0...    3.446952   
1  [0.55672677 0.53856938 0.77486174 0.53856938 0...    2.285503   
2  [0.53856938 0.88629027 0.95672677 1.96377609 2...    3.107692   
3  [1.07713877 0.67713877 1.14629228 2.90056981 0...    3.272661   
4  [1.07713877 0.26622382 0.53856938 2.90056981 0...    3.049750   
5  [0.53856938 0.53856938 0.53856938 0.53856938 0...    2.315468   
6  [0.53856938 0.53856938 0.53856938 0.53856938 0...    2.374296   

   Words quantity  TF-IDF mean  Class  True class  
0              25     2.830910      2           2  
1              20     0.589459      1           1  
2              14     1.326736      2           2  
3              12     1.267942      1           1  
4              13     1.064214      0           0  
5              10     0.538569      0           0  
6              11     0.538569      2           2

In [3]:
documents = reuters.fileids()

train_docs_id = list(filter(lambda doc: doc.startswith("train"),
                          documents))
test_docs_id = list(filter(lambda doc: doc.startswith("test"),
                         documents))
X_train = [(reuters.raw(doc_id)) for doc_id in train_docs_id]
X_test = [(reuters.raw(doc_id)) for doc_id in test_docs_id]
mlb = MultiLabelBinarizer()
Y_train = mlb.fit_transform([reuters.categories(doc_id)
                           for doc_id in train_docs_id])
print(Y_train)
Y_test = mlb.transform([reuters.categories(doc_id)
                      for doc_id in test_docs_id])
Y_train = np.argmax(Y_train, axis=1)
Y_test = np.argmax(Y_test, axis=1)
print (Y_train)

[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[ 6  0 47 ... 21 21 21]


In [4]:
batch_size = 100
sparse_categorical = 0
n_epochs = [20, 500, 50]  ## DNN--RNN-CNN
Random_Deep = [3, 0, 0]  ## DNN--RNN-CNN

RMDL.Text_Classification(X_train, Y_train, X_test, Y_test,
             batch_size=batch_size,
             sparse_categorical=True,
             random_deep=Random_Deep,
             epochs=n_epochs)

Done1
tf-idf with 26283 features
90
DNN 0
